entityMoving: true
hoistingDelay: 40
droppingDelay: 10
portcullisMaterials: [85, 101, 113]
allowFloating: true
powerBlocks: []
additionalWallMaterials: []
startSoundURL: http://mc.pepsoft.org/plugins/portecoulissante/sounds/portcullis_start.wav
upSoundURL: http://mc.pepsoft.org/plugins/portecoulissante/sounds/portcullis_up.wav
downSoundURL: http://mc.pepsoft.org/plugins/portecoulissante/sounds/portcullis_down.wav
soundEffectDistance: 24
soundEffectVolume: 50