
entityMoving: true

movingDelayBase: 30
bridgeMaterials: [43, 44, 125, 126]
maximumBoosts: 2

hoistingDelay: 40
droppingDelay: 10

portcullisMaterials: [85, 101, 113]
allowFloating: false

powerBlocks: []
additionalWallMaterials: []

soundEffectDistance: 0
soundEffectVolume: 0
soundEffects: false
